# Site settings
name: "Quire & You"
title: "Quire & You"
email: feedback@quire.io
description: "Tips and thoughts to help you achieve your dreams and get things done."
baseurl: "/blog" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: "https://quire.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: '/p/:title.html'
paginate: 15
paginate_path: "/pages/page:num/"
popular_posts: ["To Do List and Kanban: What Project Management Did Wrong", "Quire Peekaboo and GTD Methodology: A Miracle for Your Productivity Hack", "Why We Abandoned the To-Do List"]

search: true
search_full_content: true

# Build settings
# markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

category_archive: {
	path: category
}

twitter_account: 'quire_io'
locale:         en_us
icon: "/s/img/favicon.ico"
exclude:
- README.md
- Dockerfile
- installDockerBuild
- dockerBuild
- quire.conf
- startWebsite
- stopWebsite