version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "4000:80"
    volumes:
      - "blog-sync:/srv/jekyll"
      - "./quire.conf:/etc/nginx/conf.d/default.conf"
    restart: always
  jekyll:
    container_name: quire-blog
    image: protonchang/qb-x64
    volumes:
      - "blog-sync:/srv/jekyll"
    command: bash -c "cd /srv/jekyll && jekyll serve"

volumes:
    blog-sync:
      external: true
      name: blog-sync
