#!/bin/bash
# website
#
#	Purpose:
#		
#	Description:
#		
#	History:
#		Fri Dec 15 13:21:48 CST 2018, Created by jimmyshiau
#
# Copyright (C) 2017 Potix Corporation. All Rights Reserved.
docker stop blog-website
docker run --rm \
  --name blog-website \
  -p 4000:80 \
  -e "TZ=Asia/Taipei" \
  --volume="blog-sync:/srv/jekyll" \
  -it  quire-blog \
  jekyll serve
